# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70c6ddc24a0b79a10fba44add21d2c671f0050fce555f5220e5dc940aa25dfc97294da17a46c6720f7531e345d93adccb7f42e3b18e0f18a3870c43e4d9cd010

test:
  secret_key_base: e167cf2541688a1ca055dda92d471e2586c461d5251c8a2fdd5c9eb121639cf9f79825e7e433c47318b25a58b07336f01ff78852bd2f92a3d0512d0392c79418

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
